//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AboutMe.Resources.Pages.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificações.
        /// </summary>
        internal static string Certifications {
            get {
                return ResourceManager.GetString("Certifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Desenvolvimento e manutenção de sistemas utilizando .NET 8..
        /// </summary>
        internal static string CrpTecnologia1 {
            get {
                return ResourceManager.GetString("CrpTecnologia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualmente.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bacharelado Interdisciplinar em Ciência e Tecnologia.
        /// </summary>
        internal static string DegreeName {
            get {
                return ResourceManager.GetString("DegreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formação Acadêmica.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilidades Técnicas.
        /// </summary>
        internal static string HardSkills {
            get {
                return ResourceManager.GetString("HardSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguagens.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        internal static string LanguageSpeak {
            get {
                return ResourceManager.GetString("LanguageSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português - Nativo.
        /// </summary>
        internal static string LanguageSpeak1 {
            get {
                return ResourceManager.GetString("LanguageSpeak1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês - Intermediário.
        /// </summary>
        internal static string LanguageSpeak2 {
            get {
                return ResourceManager.GetString("LanguageSpeak2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maio.
        /// </summary>
        internal static string Month5 {
            get {
                return ResourceManager.GetString("Month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setembro.
        /// </summary>
        internal static string Month7 {
            get {
                return ResourceManager.GetString("Month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        internal static string Month8 {
            get {
                return ResourceManager.GetString("Month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvedor .NET Pleno.
        /// </summary>
        internal static string NetDeveloper {
            get {
                return ResourceManager.GetString("NetDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiência Profissional.
        /// </summary>
        internal static string ProfessionalExperience {
            get {
                return ResourceManager.GetString("ProfessionalExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Automatização do envio de informações em segundo plano entre o ERP e o PDV utilizando
        ///Windows Forms no .NET Framework 4.8..
        /// </summary>
        internal static string Project1 {
            get {
                return ResourceManager.GetString("Project1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Integração do ERP com a emissão de Boletos do Itaú, Santander e Bradesco, consumindo a API dos bancos e tratando o retorno de arquivos XML para o ERP utilizando .NET 6..
        /// </summary>
        internal static string Project2 {
            get {
                return ResourceManager.GetString("Project2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Integração do PDV do ERP com o Cresce Vendas, consumindo a API da plataforma e tratando o retorno de arquivos XML para o PDV utilizando .NET 6..
        /// </summary>
        internal static string Project3 {
            get {
                return ResourceManager.GetString("Project3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Integração do ERP com o e-commerce da Nuvemshop através de uma aplicação desenvolvida em .NET 8 utilizando Minimal APIs no backend, Blazor no frontend, .NET Aspire para orquestrar o desenvolvimento e Docker para o deploy..
        /// </summary>
        internal static string Project4 {
            get {
                return ResourceManager.GetString("Project4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Criação de uma aplicação interna para gerenciar as solicitações dos clientes, desenvolvida utilizando .NET 8 com MVC, autenticação JWT no backend, Blazor no frontend, .NET Aspire para orquestrar o desenvolvimento e IIS para o deploy..
        /// </summary>
        internal static string Project5 {
            get {
                return ResourceManager.GetString("Project5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projetos Desenvolvidos:.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal de Corretagem de Imóveis.
        /// </summary>
        internal static string RelevantProject1 {
            get {
                return ResourceManager.GetString("RelevantProject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projetos Relevantes.
        /// </summary>
        internal static string RelevantProjects {
            get {
                return ResourceManager.GetString("RelevantProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsabilidades.
        /// </summary>
        internal static string Responsibilities {
            get {
                return ResourceManager.GetString("Responsibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Desenvolvimento de soluções web e desktop com .NET, ASP.NET e Blazor..
        /// </summary>
        internal static string Responsibility1 {
            get {
                return ResourceManager.GetString("Responsibility1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Implementação de APIs RESTful..
        /// </summary>
        internal static string Responsibility2 {
            get {
                return ResourceManager.GetString("Responsibility2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Integração e manutenção de sistemas legados..
        /// </summary>
        internal static string Responsibility3 {
            get {
                return ResourceManager.GetString("Responsibility3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Manutenção em relatórios utilizando Delphi/Pascal..
        /// </summary>
        internal static string Responsibility4 {
            get {
                return ResourceManager.GetString("Responsibility4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Manutenção em triggers, procedures e tabelas do banco de dados Firebird..
        /// </summary>
        internal static string Responsibility5 {
            get {
                return ResourceManager.GetString("Responsibility5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvedor .NET orientado a resultados com 3 anos de experiência, especializado em construção e integração de aplicações corporativas fullstack..
        /// </summary>
        internal static string ResumeText1 {
            get {
                return ResourceManager.GetString("ResumeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacidade comprovada de entregar soluções robustas utilizando o ecossistema .NET para atender às necessidades dos clientes..
        /// </summary>
        internal static string ResumeText2 {
            get {
                return ResourceManager.GetString("ResumeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualmente, estou aprimorando minha expertise técnica por meio de um Bacharelado Interdisciplinar em Ciência e Tecnologia..
        /// </summary>
        internal static string ResumeText3 {
            get {
                return ResourceManager.GetString("ResumeText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumo Profissional.
        /// </summary>
        internal static string ResumeTitle {
            get {
                return ResourceManager.GetString("ResumeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analista de Suporte.
        /// </summary>
        internal static string SupportAnalyst {
            get {
                return ResourceManager.GetString("SupportAnalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Análise de consultas SQL no Firebird..
        /// </summary>
        internal static string SupportAnalyst1 {
            get {
                return ResourceManager.GetString("SupportAnalyst1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Análise de código fonte em Delphi..
        /// </summary>
        internal static string SupportAnalyst2 {
            get {
                return ResourceManager.GetString("SupportAnalyst2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Análise de situações referentes à emissão de notas fiscais eletrônicas..
        /// </summary>
        internal static string SupportAnalyst3 {
            get {
                return ResourceManager.GetString("SupportAnalyst3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Atendimento via software de acesso remoto aos clientes..
        /// </summary>
        internal static string SupportAnalyst4 {
            get {
                return ResourceManager.GetString("SupportAnalyst4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET, C#, Blazor, Java, Delphi, Firebird, MySQL, PostgreSQL, Github e Docker..
        /// </summary>
        internal static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinta-se à vontade para entrar em contato comigo em: .
        /// </summary>
        internal static string TextToContact {
            get {
                return ResourceManager.GetString("TextToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferramentas e Bancos de Dados.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
    }
}
